### ISSUE TITLE
Txt verification code doesn't work in the Isle of Man 0044 7624 ......

### ISSUE THREAD

**Issue by 3rdwiki** [twitter/twitter-server#22]
Trying for several hours with various mobile phones that have never even visited twitter befoe, I tried to get verified on the web ( not using a phone to use twitter) with a 0044 7624 ****** number and the code never came through.

You desperately need to include a message to say the phone has been used before,or accept the above types of numbers for the Isle of Man.

This seriously grinds my gears.

**Comment by mosesn** [comment]
I'm sorry to hear about that, but I suspect that you'll have better luck with [twitter support][0].  That system at twitter isn't related to TwitterServer.

[0]: https://support.twitter.com/
