### ISSUE TITLE
Where can I download ../parents/scala-parent-2104/pom.xml?

### ISSUE THREAD

**Issue by cycorey** [twitter/twitter-server#25]
in the pom.xml
thanks!

**Comment by mosesn** [comment]
Unfortunately, you can't build twitter-server with maven, only with sbt.

**Comment by cycorey** [comment]
I build it with sbt successful, thanks!

**Comment by kevinoliver** [comment]
I'm going to remove the pom from the project so we don't confuse people in the future. Thanks for reporting it.
