### ISSUE TITLE
expose process environment variables from /admin

### ISSUE THREAD

**Issue by olix0r** [twitter/twitter-server#26]
i'd like a way to capture a process's environment variables and system properties at runtime from its admin interface.

i'm happy to implement this myself--just wanted to document the issue on this so it's tracked.

**Comment by kevinoliver** [comment]
sounds like a good idea.

**Comment by mosesn** [comment]
Do you want to stick it in /admin/registry.json?

**Comment by vkostyukov** [comment]
Fixed by #27.
