### ISSUE TITLE
How to send response using stream?

### ISSUE THREAD

**Issue by cycorey** [twitter/twitter-server#29]
I want to response text using stream,not :
response.setContent(copiedBuffer("hello", Charsets.Utf8))
Future.value(response)

but like:
response.write(...)
response.flush()
response.write(...)
response.flush()

thanks!

**Comment by mosesn** [comment]
@cycorey this question is probably better suited for the [finaglers@][0] mailing list.  Folks will be happy to help you there :+1: 

[0]: https://groups.google.com/forum/#!forum/finaglers
