### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by ligadata-dhaval** [twitter/twitter-server#35]
I am using twitter's 'application only auth' for my application. In my code I try to create user list for which I do not have access. However, instead of getting a authentication or access issue, I am getting the below error:

This code is used when requests are being denied due to update limits

**Comment by kevinoliver** [comment]
@ligadata-dhaval looks like the error got eaten along the way. That said, I'm not sure the TwitterServer OSS project is the right location for your question. Maybe https://dev.twitter.com/ ?
