### ISSUE TITLE
Document how to use other kinds of stats

### ISSUE THREAD

**Issue by mosesn** [twitter/twitter-server#38]
The TwitterServer docs only document counters, not histograms or gauges.

**Comment by kevinoliver** [comment]
I think a link to the util-stats docs would suffice:
http://twitter.github.io/util/guide/util-stats/basics.html

**Comment by Abhik1998** [comment]
Can I add those?

**Comment by mosesn** [comment]
Yep, go ahead!  Maybe add them here: https://twitter.github.io/twitter-server/Features.html#metrics
