### ISSUE TITLE
2.12-ification

### ISSUE THREAD

**Issue by mosesn** [twitter/twitter-server#41]
In order to support 2.12, we need to add crossScalaVersions to Build.scala, and make sure everything compiles.  Not every scala library will be built against the current snapshot, so we may have to support different versions from 2.11 to 2.12.  If part of an API has churned (scalacheck in particular is susceptible to this) we may need to upgrade the 2.11 library version to make progress.  If that happens, contact me (@mosesn) and I'll navigate the upgrade for you–it's a little complicated because we will need to upgrade all of our internal libraries, not just scrooge.  Please note that most of this upgrade will not be feasible until we have a portion of util and finagle already upgraded.

**Comment by taylorleese** [comment]
Related: https://github.com/twitter/finagle/issues/505

**Comment by mosesn** [comment]
finished, h/t @jcrossley!  see https://github.com/twitter/twitter-server/commit/f947f47552b70b1d34797332e63fa7800f2b62d6
