### ISSUE TITLE
Upgrade to Jackson version and remove deprecated API

### ISSUE THREAD

**Issue by ikhoon** [twitter/twitter-server#43]
### Problem

`Lf2SpacesIndenter` in [DefaultPrettyPrinter](http://fasterxml.github.io/jackson-core/javadoc/2.6/com/fasterxml/jackson/core/util/DefaultPrettyPrinter.htm) deprecated since 2.5 and removed in 2.7. 

> DefaultPrettyPrinter.Lf2SpacesIndenter
Deprecated. 
Since 2.5 use DefaultIndenter instead

Some libraries which depends on jackson 2.7 have trouble like below.
```

java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/DefaultPrettyPrinter$Lf2SpacesIndenter
```

https://github.com/twitter/twitter-server/blob/a569edc24aca5935389d8ae498aa5abdb05cdcc1/src/main/scala/com/twitter/server/util/JsonConverter.scala#L13
```scala
  private[this] val writer = {
    val mapper = new ObjectMapper().registerModule(DefaultScalaModule)
    val printer = new DefaultPrettyPrinter
    // this code not valid in jackson 2.7
    printer.indentArraysWith(new DefaultPrettyPrinter.Lf2SpacesIndenter) 
    mapper.writer(printer)
  }
```

### Solution
```scala
  private[this] val writer = {
    val mapper = new ObjectMapper().registerModule(DefaultScalaModule)
    val printer = new DefaultPrettyPrinter
   // upgrade jackson verison and use new API
    printer.indentArraysWith(DefaultIndenter.SYSTEM_LINEFEED_INSTANCE) 
    mapper.writer(printer)
  }
```
Related issue : twitter/finatra#276

**Comment by mosesn** [comment]
@ikhoon as @cacoco mentioned, we're moving to 2.6.5 internally, so I think we'll be able to change after that.  do you want to make a PR with the code change that you've described?

**Comment by ikhoon** [comment]
@mosesn After upgrade 2.6.5, I will be pleased to make code and PR.
Thanks for your fast feedback! :blush:

**Comment by roanta** [comment]
Hi @ikhoon, we upgraded to 2.6.5 in https://github.com/twitter/twitter-server/commit/de4b44b612f1f402b27a3b59c1f0918f10bf0e14

You're welcome to open a PR which fixes the deprecated APIs!

**Comment by ikhoon** [comment]
@roanta The upgrade is good new and I am wait for that.  
I will fix the deprecated API and make PR :-)
Thanks.
👍
