### ISSUE TITLE
support  HTTP persistent connection?

### ISSUE THREAD

**Issue by cycorey** [twitter/twitter-server#44]
Is this lib support  HTTP persistent connection(https://en.wikipedia.org/wiki/HTTP_persistent_connection)?

### Expected behavior

I use this http client(https://github.com/AsyncHttpClient/async-http-client), want to know how to config twitter server to support HTTP persistent connection.

thanks!

**Comment by mosesn** [comment]
@cycorey if you're trying to build an http server, you probably want to use [finatra][0] or [finagle][1].  TwitterServer is for building an admin server, and pairs nicely with finatra or finagle.  Both finatra and finagle support persistent connections.

[0]: https://github.com/twitter/finatra
[1]: https://github.com/twitter/finagle

**Comment by mosesn** [comment]
@cycorey I think we answered your question, so I'm going to close this.  feel free to reopen if we didn't!
