### ISSUE TITLE
Logging Trait mixin: asyncFlag and asyncMaxSizeFlag unavailable

### ISSUE THREAD

**Issue by basert** [twitter/twitter-server#46]
When using the logging trait as a mixin, the asyncFlag and asyncMaxSizeFlag are unavailable due to being marked as private. All other flags are protected so they can get accessed in the child.

### Expected behavior

Accessing asyncFlag and  asyncMaxSizeFlag should be possible.

### Actual behavior

Both flags are marked as private.

### Steps to reproduce the behavior

Override handlers def as advised in the method comment.

```scala
package util

import com.twitter.logging.{ConsoleHandler, Handler, QueueingHandler, SyslogHandler, Logging => TwitterLogging}

trait Logging {
  self: TwitterLogging =>

  override def handlers: List[() => Handler] = {
    val output = outputFlag()
    val level = Some(levelFlag())
    val consoleHandler = ConsoleHandler(defaultFormatter, level)
    val syslogHandler = SyslogHandler(output, SyslogHandler.DEFAULT_PORT, defaultFormatter, level)

    if (asyncFlag()) {
      List(
        QueueingHandler(consoleHandler, asyncMaxSizeFlag(), inferClassNamesFlag()),
        QueueingHandler(syslogHandler, asyncMaxSizeFlag(), inferClassNamesFlag())
      ) 
    } else {
      List(
        consoleHandler,
        syslogHandler
      )
    }
  }
}
```

**Comment by mosesn** [comment]
@basert seems reasonable, do you want to tackle this?  it would be a PR in the twitter/util repo.

**Comment by basert** [comment]
Opened a PR.

**Comment by ryanoneill** [comment]
Hi @basert, now that your pull request has been submitted, is it ok to close this issue?

**Comment by basert** [comment]
Yes, thanks :)
