### ISSUE TITLE
Support for SLF4J logging

### ISSUE THREAD

**Issue by kovszilard** [twitter/twitter-server#50]
Are there any plans to move towards SLF4J instead of java.util.logging? As I see twitter-util already has an implementation and in the readme, they say "It is recommended that users move to using util-slf4j-api over util-logging."

**Comment by mosesn** [comment]
Yep, it's a work in progress.  We mentioned it in our [spring planning][0] blog post, which has other work we're planning on tackling you might be interested in too.

[0]: http://finagle.github.io/blog/2017/03/20/spring-planning/

**Comment by cacoco** [comment]
Merged in 906ae7df2d32e329ba12ec540b45274898cf5862. See documentation: https://twitter.github.io/twitter-server/Features.html#logging
