### ISSUE TITLE
Server shutdown - Get instead of POST

### ISSUE THREAD

**Issue by teodor-pripoae** [twitter/twitter-server#54]
When I click shutdown in the admin server and click OK the request sent is GET instead of POST. The UI should be updated to send POST request.

### Expected behavior

Shutdown the server

### Actual behavior

Server returns `405 Method Not Allowed`

### Steps to reproduce the behavior

- Run the server using finatra 2.12.0
- Go to admin server
- Click shutdown link in the `utilities` section
- Press Ok

**Comment by cacoco** [comment]
@teodor-pripoae thanks for the report, we'll take a look.

**Comment by smlance** [comment]
This should be fixed with https://github.com/twitter/twitter-server/commit/d93665cc97d7f4a3715c193bfe2d0e8488c973aa.
