### ISSUE TITLE
AdminHttpServer.routes are not registered to admin server

### ISSUE THREAD

**Issue by krrrr38** [twitter/twitter-server#61]
Before following commit, we can add admin route by overriding `def routes`. currently overriding `def routes` has no meanings, it's breaking changes. Now we should use addAdminRoute, so propose that removing def routes.

https://github.com/twitter/twitter-server/commit/206df64a6046bebedf9073526602352a4277a6e4#commitcomment-36904390

### Expected behavior

`AdminHttpServer.routes` registered to admin server.
(But currently we should use addAdminRoute, so it's better to remove `AdminHttpServer.routes`)

### Actual behavior

If override `AdminHttpServer.routes`, the routes are not registered to admin server

### Steps to reproduce the behavior

```scala
class SomeServer extends TwitterServer with AdminHttpServer {
  override def routes() = ... // this is not registered to admin server
}
```

**Comment by yufangong** [comment]
Hi @krrrr38, thanks for the report!
The current behavior is expected. We have some changes to switch `routes` from a setter to a getter. And replace the set routes with `AdminHttpServer. addAdminRoute` as you pointed out. 
Sorry that we forget to mention this in CHANGELOG, we will soon patch the notice and probably add some scaladoc for the method.

**Comment by yufangong** [comment]
Hey @krrrr38, we patched this issue here: https://github.com/twitter/twitter-server/commit/7093858809146e4aa01421141637708b3a86a591. Closing this issue now, but if there is any remaining problem, feel free to open another one. Thanks!
