### ISSUE TITLE
Where is `snowflake id` in this repo?

### ISSUE THREAD

**Issue by fzyzcjy** [twitter/twitter-server#64]
Hi thanks for the repo! I wonder where is `snowflake id` in this repo? I came from the [old snowflake](https://github.com/twitter-archive/snowflake) repo, which said that the newer code is here. But after a search I cannot find anything related to id generation :(

### Expected behavior

See the snowflake id source code.

### Actual behavior

Not see.

### Steps to reproduce the behavior

Look at it.

**Comment by cacoco** [comment]
@fzyzcjy I think that comment is being misinterpreted. The archived README said the new snowflake project will be **based on TwitterServer** services not that there's any new code here. As mentioned in the README here, this is an application container with a lifecycle and is not related to snowflake ID generation. As of now, there is no replacement for the archived library, sorry.

Hope that helps!

Thanks.

**Comment by fzyzcjy** [comment]
Oh get it... Thanks all the same!
