### ISSUE TITLE
/admin/metrics.json endpoint?

### ISSUE THREAD

**Issue by plelevier** [twitter/twitter-server#7]
Hello!

I'm trying to access to the metrics endpoint described in the documentation :
http://twitter.github.io/twitter-server/Features.html#metrics

It should be under /admin/metrics.json, but it doesn't work for me (I'm using 1.0.1, and simply trying the AdvancedServer code).
Is this endpoint really implemented?

There's no handler for this endpoint in the Admin.scala source code :
https://github.com/twitter/twitter-server/blob/master/src/main/scala/com/twitter/server/Admin.scala

Everything else seems working fine

**Comment by KazukiMorozumi** [comment]
I faced same problem, but it was solved by adding com.twitter.finagle-stats dependency.
Like this.
```
libraryDependencies += "com.twitter" %% "finagle-stats" % "7.0.0"
```
